# Generated by Django 4.2.1 on 2023-05-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nazwa')),
                ('scientific_name', models.CharField(max_length=64, verbose_name='nazwa naukowa')),
                ('weight', models.IntegerField(null=True, verbose_name='waga [g]')),
                ('length', models.IntegerField(null=True, verbose_name='długość [cm]')),
                ('species', models.CharField(max_length=64, verbose_name='gatunek')),
            ],
        ),
        migrations.CreateModel(
            name='BirdStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='miejsce')),
                ('city', models.CharField(max_length=64, null=True, verbose_name='miasto')),
                ('country', models.CharField(max_length=64, verbose_name='kraj')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('bird_name', models.ManyToManyField(through='birdstandy.BirdStand', to='birdstandy.place')),
            ],
        ),
        migrations.AddField(
            model_name='birdstand',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdstandy.user'),
        ),
        migrations.AddField(
            model_name='birdstand',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdstandy.bird'),
        ),
        migrations.AddField(
            model_name='birdstand',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdstandy.place'),
        ),
        migrations.CreateModel(
            name='BirdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdstandy.bird')),
            ],
        ),
    ]
