# Generated by Django 4.2.1 on 2023-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdstandy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.IntegerField(choices=[(1, 'pustółka'), (2, 'drozd'), (3, 'czyżyk'), (4, 'rudzik'), (5, 'sroka'), (6, 'wróbel'), (7, 'kruk')], verbose_name='nazwa'),
        ),
    ]
