# Generated by Django 4.2.1 on 2023-05-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdstandy', '0002_alter_bird_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdstand',
            old_name='first_name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bird_name',
            new_name='places',
        ),
    ]
