# Generated by Django 4.2.1 on 2023-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdstandy', '0003_rename_first_name_birdstand_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nazwa'),
        ),
    ]
