# Generated by Django 4.2.1 on 2023-05-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdstandy', '0004_alter_bird_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdstand',
            old_name='name',
            new_name='bird',
        ),
        migrations.RenameField(
            model_name='birdstand',
            old_name='user',
            new_name='birdstands',
        ),
    ]
