# Generated by Django 4.2.1 on 2023-05-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdstandy', '0006_rename_birdstands_birdstand_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Watcher',
        ),
        migrations.RenameField(
            model_name='birdstand',
            old_name='user',
            new_name='watcher',
        ),
    ]
