# Generated by Django 4.2.1 on 2023-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdstandy', '0007_rename_user_watcher_rename_user_birdstand_watcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='długość [cm]'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='species',
            field=models.CharField(blank=True, max_length=64, verbose_name='gatunek'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='waga [g]'),
        ),
    ]
