# Generated by Django 4.2.1 on 2023-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdstandy', '0008_alter_bird_length_alter_bird_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdphoto',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
